dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.8"
install:
  - pushd /tmp
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip -O z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip
  - unzip z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip
  - popd
  - export PATH=/tmp/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04/bin/:$PATH
  - export PYTHONPATH=/tmp/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04/bin/python/:$PYTHONPATH
  - pip install -r requirements.txt
  - wget https://github.com/CVC4/CVC4/releases/download/1.7/cvc4-1.7-x86_64-linux-opt
  - chmod +x cvc4-1.7-x86_64-linux-opt
script: make test
